### ISSUE TITLE
Trying to implement the emeter emulation in Tasmota-Berry

### ISSUE THREAD

**Issue by FransOv** [Roeland54/SMA-Energy-Meter-emulator#13]
I'm trying to implement the SMA meter emulation in Tasmota-Berry, using your implementation as a guideline. I noticed a few differences from the SMA publication, but assume that your working implementation is the correct one. I think I have the correct payload, but my SMA Tripower inverter keeeps saying "Invalid communication" on the "Meter on Speedwire" tab of the "Instantaneous Values" page.
An example of my payload is: 
```
bytes("534D4100000402A000000001006000106069010E2A9D577100002EF700010801000000060A081E0000010802000000036DE92300000208010000000337A22B0000020802000000073E6667000001040000000000000204000000127C00030000000000000004000000000000900000000102045200000000")
```
I must be doing something wrong but cant find out what. Can you help me?

**Comment by Roeland54** [comment]
I am afraid I am not really able to help you. The composition of the data packet is completely based on the implementation I have [found here. ](https://github.com/jtuemmler/sml2emeter) I have sometimes warnings in my event viewer "
Communication fault with meter unit" but overall it seems to work.

Maybe if you could try the add-on and see if the same issues occur?

**Comment by FransOv** [comment]
I used a stripped down version of your software to send some dummy measurements to the inverter, but no luck, still Invalid communication on the inverter. I compared the packets and those I send from the ESP are identical to those send by your software. So the problem lies elsewhere.
